export const REGISTER_SUCCESS = "REGISTER_SUCCESS"

export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS"

export const INSERT_POKEMON = "INSERT_POKEMON"

export const UPDATE_POKEMON="UPDATE_POKEMON"

export const INSERT_LOGS = "INSERT_LOGS"

export const GET_LOGS = "GET_LOGS"

export const MY_POKEMON = "MY_POKEMON"

export const ENEMY_POKEMON = "ENEMY_POKEMON"